[package]
name = "openapi-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.38"
color-eyre = "0.6.3"
enum-map = "2.7.3"
indexmap = "2.6.0"
openapiv3 = "2.0.0"
regex = "1.11.1"
serde_json = "1.0.133"
strum = { version = "0.27.1", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.38"
regex = "1.11.1"
